name: Publish

on:
    push:
        branches: [ master ]

jobs:
    distribute:
        name: Distribute app bundle to Play Store
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: 11
                  distribution: 'temurin'
                  cache: gradle

            - name: Version bump
              uses: chkfung/android-version-actions@v1.1
              with:
                gradlePath: app/build.gradle
                versionCode: ${{ github.run_number }}

            - name: Assemble Release Bundle
              run: ./gradlew bundleRelease

            - name: Sign Release
              uses: r0adkll/sign-android-release@v1
              with:
                  releaseDirectory: app/build/outputs/bundle/release
                  signingKeyBase64: ${{ secrets.BASE64_STORE_FILE }}
                  alias: ${{ secrets.KEY_ALIAS_FRIENDS }}
                  keyStorePassword: ${{ secrets.STORE_PASS_FRIENDS }}
                  keyPassword: ${{ secrets.KEY_PASS_FRIENDS }}

            - name: Setup authorization with Google Play Store
              run: echo '${{ secrets.GOOGLE_PLAY_API_KEY }}' > service_account.json

            - name: Deploy to internal
              uses: r0adkll/upload-google-play@v1.0.19
              with:
                  serviceAccountJson: service_account.json
                  packageName: i.herman
                  releaseFiles: app/build/outputs/bundle/release/app-release.aab
                  track: internal
                  status: 'draft'
                  whatsNewDirectory: whatsNewDirectory/